User.create(email:"user1@gmail.com" , password:"0000" , age:"10" , address:"1234", first_name:"user1" , last_name:"last1")
User.create(email:"user2@gmail.com" , password:"0000" , age:"25" , address:"1234", first_name:"user2" , last_name:"last2")
User.create(email:"user3@gmail.com" , password:"0000" , age:"43" , address:"1234", first_name:"user3" , last_name:"last3")
User.create(email:"user4@gmail.com" , password:"0000" , age:"96" , address:"1234", first_name:"user4" , last_name:"last4")
Item.create(name:"Le Marteau de Thor" , description:"Super outil, toujours performant pour tous types de traveaux!!" , price:150, user_id: 1 )
Item.create(name:"Nimbus 2000" , description:"Bien mieux qu'un aspirateur Dyson" , price:50, user_id: 2 )
Item.create(name:"la VERITABLE cape de Frodon" , description:"A porter en toutes saisons" , price:75, user_id: 3 )
Item.create(name:"Faucon Millenium" , description:"Pour un séjour inoubliable!" , price:989, user_id: 4 )
